### ISSUE TITLE
Make error annotation configurable

### ISSUE THREAD

**Issue by strazto** [adambirds/docker-compose-action#11]
On a failed test, the error annotation is used, which is basically the error stringified.

https://github.com/adambirds/docker-compose-action/blob/cf2e51f76beacad15b1046de89ee2eb22ea70bac/main.js#L54

Some test runners natively support logging errors to github action annotations, so this extra failure annotation is redundant, and noisy.

It'd be nice if it was optional

**Comment by adambirds** [comment]
@strazto i'm going to set the default as is currently, and allow you to switch it off. I will maybe add a setting `annotate` and you need to set to false to turn off.
