### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by seplee** [adambirds/docker-compose-action#17]
Hi Adam, Great work! Can you add a license file? I would like to know where I am legally safe to use this.

**Comment by adambirds** [comment]
@seplee i thought it had one but will sort one later for you!

**Comment by adambirds** [comment]
Done @seplee

**Comment by seplee** [comment]
Thanks @adambirds 😸 
⚡⚡That was fast!⚡⚡

**Comment by adambirds** [comment]
I'm about to release v1.5.0 shortly so you may wanna start using it with that version as it will be live within the hour.
