### ISSUE TITLE
Fails on simple file

### ISSUE THREAD

**Issue by harshraj22** [adambirds/docker-compose-action#2]
Actions run result: https://github.com/harshraj22/smallProjects/actions/runs/4650998949/jobs/8230328773
Not sure what is wrong

the test command `test-command: "nc -vz localhost 9092"` pings the kafka server. 
tried with both, test-container as "ubuntu" and "broker" (the name given to kafka microservice in docker compose)

**Comment by adambirds** [comment]
@harshraj22 i've been experiencing the same issue with my tests on one of my projects which I'm currently investigating. I think I may need to add a short delay between the `docker-compose up` command finishing and the tests executing as the fact we are getting no output in the error leads me to think that we're executing the tests before the containers are fully ready. Will ping you when sorted.

**Comment by harshraj22** [comment]
Please also consider the cases when docker-compose file spins up lots of microservices and the whole system takes 5-10 minutes to spin up. Hardcoding a time value like 1-2 minute of delay might not be the best workaround

**Comment by adambirds** [comment]
@harshraj22 do you have an example `docker-compose.yml` yaml file which does load lost of services? The one I'm working with does spin up 5 containers anyway. What I may do is specify a default but add an option to override that.

**Comment by harshraj22** [comment]
@adambirds https://github.com/harshraj22/Dis-Sim

**Comment by adambirds** [comment]
@harshraj22 could you test with a simple file by poullinmg the action from `adambirds/docker-compose-action@add-timeout` and let me know if the simple one works. Thanks

**Comment by adambirds** [comment]
Fixed by #4. This now works by a simple file, will be in the next release.
