### ISSUE TITLE
Run Integration/ Load test

### ISSUE THREAD

**Issue by harshraj22** [adambirds/docker-compose-action#3]
Can I run Load/ Integration test on a project hosting multiple microservice with this workflow ?
Say my project is :https://github.com/harshraj22/Dis-Sim 
and my test is in test.py or set of tests are in `tests/` dir.

If yes, can you share sample code yaml file ?

**Comment by adambirds** [comment]
@harshraj22 check README.md for example workflow for multiple containers.
