### ISSUE TITLE
When testing locally with act tool getting error

### ISSUE THREAD

**Issue by devSajan** [adambirds/docker-compose-action#6]
::error::compose up failed {"errno":-2,"code":"ENOENT","syscall":"spawn docker-compose","path":"docker-compose","spawnargs":["-f","./docker-compose.yml","up","-d"]}

Here we are trying to spawn docker-compose but as per latest  version it's `docker compose`

**Comment by adambirds** [comment]
Hi @devSajan,

I'll need some more information regarding this such as system docker versions etc as I'm running this daily in my actions and not having any issues with it unless something has changed in the last 6 hours.

**Comment by adambirds** [comment]
An example workflow would also be useful.

**Comment by devSajan** [comment]
Docker Compose version 2.20.2+azure-1

I am testing it locally with this tool https://github.com/nektos/act

**Comment by adambirds** [comment]
I will just pin my dependency version harder then as I'm not looking to update to using the latest version of docker compose as this isn't causing any issues yet. The issue will be with that third party project installing a newer version than my project asks for. I'm quite happy leaving it as it is for now.

**Comment by adambirds** [comment]
@devSajan I probably won't get round to this for a bit though. It will work fine in actual GitHub Actions as I'm using it every day without an issue.
