### ISSUE TITLE
Sporadic failure with run command - not deterministic

### ISSUE THREAD

**Issue by samthomson** [adambirds/docker-compose-action#7]
My test command randomly fails. I have `test-command: "yarn run test"`. Which works - but not always.  It will fail, then I re-run failed jobs and it passes (with no code change).

When it fails, it says jest is not found (what I run my tests via).

Here's some output:
```
compose started
testContainer app
testCommand yarn run test
yarn run v1.22.19
$ NODE_ENV=TESTING jest --detectOpenHandles
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

/bin/sh: jest: not found
error Command failed with exit code 127.

Error: tests failed {"exitCode":127,"err":"/bin/sh: jest: not found\nerror Command failed with exit code 127.\n","out":"yarn run v1.22.19\n$ NODE_ENV=TESTING jest --detectOpenHandles\ninfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\n"}
```

And here's my innocuous test script (from within a package.json file):
`"test": "NODE_ENV=TESTING jest --detectOpenHandles",`

And here's the whole task runner:
```
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: adambirds/docker-compose-action@v1.3.0
        with:
          compose-file: "./docker-compose-test.yml"
          down-flags: "--volumes"
          test-container: app
          test-command: "yarn run test"
          ```

Any idea what could be causing this, or how to address?

**Comment by adambirds** [comment]
I'll be honest I'm not sure. I've never used jest. I will be upgrading this to use node20 soon, maybe this will help with your issues. All the tests I've used for are python based and never had an issue with them.

**Comment by samthomson** [comment]
Okay no worries. Thanks for your comment anyway :)

**Comment by adambirds** [comment]
Closing as now nupgraded to node20 and issue seemed related to users setup rather than this action.
